spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:1111/lesprom
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
      #ddl-auto: create
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

jwt:
  header: Authorization
  secret: person
  expiration: 604800