alter table if exists employee_workplace
    drop constraint if exists buffer_employee_fk;
alter table if exists employee_workplace
    drop constraint if exists buffer_workplace_fk;
alter table if exists order_workplace
    drop constraint if exists buffer_order_fk;
alter table if exists order_workplace
    drop constraint if exists buffer_workplace_fk;
alter table if exists time_of_employee_on_order
    drop constraint if exists time_of_employee_on_order_employee_fk;
alter table if exists time_of_employee_on_order
    drop constraint if exists time_of_employee_on_order_order_fk;
alter table if exists user_role
    drop constraint if exists buffer_role_fk;
alter table if exists user_role
    drop constraint if exists buffer_user_fk;
drop table if exists baguette cascade;
drop table if exists cutter cascade;
drop table if exists employee cascade;
drop table if exists employee_workplace cascade;
drop table if exists order_on_create cascade;
drop table if exists order_workplace cascade;
drop table if exists role cascade;
drop table if exists time_of_employee_on_order cascade;
drop table if exists user_role cascade;
drop table if exists usr cascade;
drop table if exists workplace cascade;

create table baguette
(
    id            int8 generated by default as identity,
    baguette_name varchar(255),
    primary key (id)
);

create table cutter
(
    id          int8 generated by default as identity,
    cutter_name varchar(255),
    primary key (id)
);

create table employee
(
    id        int8 generated by default as identity,
    full_name varchar(255),
    primary key (id)
);

create table employee_workplace
(
    id_workplace int8 not null,
    id_employee  int8 not null,
    primary key (id_employee, id_workplace)
);

create table order_on_create
(
    id                int8 generated by default as identity,
    finish_date       date,
    number_order      varchar(255),
    order_description varchar(2048),
    start_date        date,
    id_baguette       int8,
    id_cutter         int8,
    primary key (id)
);

create table order_workplace
(
    id_workplace int8 not null,
    id_order     int8 not null,
    primary key (id_order, id_workplace)
);

create table role
(
    id   int8 generated by default as identity,
    role varchar(255),
    primary key (id)
);

create table time_of_employee_on_order
(
    id               int8 generated by default as identity,
    time_finish_work timestamp,
    time_start_work  timestamp,
    id_employee      int8,
    id_order         int8,
    primary key (id)
);

create table user_role
(
    id_user int8 not null,
    id_role int8 not null,
    primary key (id_role, id_user)
);

create table usr
(
    id       int8 generated by default as identity,
    password varchar(255),
    username varchar(255),
    primary key (id)
);

create table workplace
(
    id             int8 generated by default as identity,
    name_workplace varchar(255),
    primary key (id)
);

alter table if exists employee_workplace
    add constraint buffer_employee_fk foreign key (id_employee) references employee;
alter table if exists employee_workplace
    add constraint buffer_workplace_fk foreign key (id_workplace) references workplace;

alter table order_on_create
    add constraint order_baguette_fk foreign key (id_baguette) references baguette;
alter table order_on_create
    add constraint order_cutter_fk foreign key (id_cutter) references cutter;

alter table if exists order_workplace
    add constraint buffer_order_fk foreign key (id_order) references order_on_create;
alter table if exists order_workplace
    add constraint buffer_workplace_fk foreign key (id_workplace) references workplace;

alter table if exists time_of_employee_on_order
    add constraint time_of_employee_on_order_employee_fk foreign key (id_employee) references employee;
alter table if exists time_of_employee_on_order
    add constraint time_of_employee_on_order_order_fk foreign key (id_order) references order_on_create;

alter table if exists user_role
    add constraint buffer_role_fk foreign key (id_role) references role;
alter table if exists user_role
    add constraint buffer_user_fk foreign key (id_user) references usr;


insert into public.usr (password, username)
values ('elkin', 'elkin'),
       ('ivanov', 'ivanov'),
       ('petrov', 'petrov'),
       ('sidorov', 'sidorov');

create extension if not exists pgcrypto;
update usr
set password = crypt(password, gen_salt('bf', 8));

insert into public.role (role)
values ('USER'),
       ('ADMIN');

insert into public.user_role (id_user, id_role)
values (1, 1),
       (2, 1),
       (3, 1),
       (4, 1),
       (1, 2);

insert into public.baguette (baguette_name)
values ('фигурный'),
       ('прямой');

insert into public.cutter (cutter_name)
values ('Пазовая фреза'),
       ('Кромочная фреза');

insert into public.workplace (name_workplace)
values ('Столярный участок'),
       ('Участок шлифовки'),
       ('Малярный участок'),
       ('Корпусной участок'),
       ('Участок сборки'),
       ('Участок упаковки'),
       ('Участок отгрузки');

insert into public.employee (full_name)
values ('Алексеев'),
       ('Иванов'),
       ('Петров'),
       ('Сидоров'),
       ('Михайлов'),
       ('Выбегалло'),
       ('Ойра-ойра'),
       ('Амперян'),
       ('Корнеев'),
       ('Привалов'),
       ('Кокоберидзе'),
       ('Катцман'),
       ('Воронин'),
       ('Горчаков');

insert into public.employee_workplace (id_workplace, id_employee)
values (1, 1),
       (1, 2),
       (2, 3),
       (2, 4),
       (3, 5),
       (3, 6),
       (4, 7),
       (4, 8),
       (5, 9),
       (5, 10),
       (6, 11),
       (6, 12),
       (7, 13),
       (7, 14);

insert into public.order_on_create (number_order, start_date, finish_date, id_baguette, id_cutter, order_description)
values ('1111a', '2022-01-05', '2022-02-05', 1, 1, 'цвет = синий, массив = дсп, шпон = дуб, радиус = 3, стекло = есть, переплет = есть'),
       ('2222b', '2022-01-01', '2022-02-02', 1, 2, 'цвет = серый, массив = ясень, шпон = красное дерево, радиус = 2,5, стекло = есть, переплет = нет'),
       ('3333c', '2022-03-15', '2022-05-21', 2, 1, 'цвет = голубой, массив = клен, шпон = дуб, радиус = 2,5, стекло = есть, переплет = нет'),
       ('4444d', '2022-06-08', '2022-07-28', 2, 2, 'цвет = коричневый, массив = ясень, шпон = клен, радиус = 1,5, стекло = есть, переплет = нет'),
       ('5555e', '2022-04-19', '2022-05-02', 2, 1, 'цвет = черный, массив = сосна, шпон = дуб, радиус = 4, стекло = нет, переплет = нет');

insert into public.order_workplace (id_order, id_workplace)
values (1, 1),
       (1, 2),
       (1, 3),
       (2, 1),
       (2, 5),
       (2, 6),
       (3, 2),
       (3, 3),
       (3, 7),
       (4, 3),
       (4, 4),
       (4, 7),
       (5, 4),
       (5, 5),
       (5, 6);

insert into public.time_of_employee_on_order (id_order, id_employee, time_start_work, time_finish_work)
values (1, 1, '2022-08-19 09:36:49.000000', '2022-08-20 09:36:49.000000'),
       (1, 3, '2022-08-18 09:36:49.000000', '2022-08-20 09:36:49.000000'),
       (2, 10, '2022-08-19 09:36:49.000000', '2022-08-20 09:36:49.000000'),
       (2, 11, '2022-08-15 09:36:49.000000', '2022-08-20 09:36:49.000000'),
       (3, 4, '2022-08-14 09:36:49.000000', '2022-08-20 09:36:49.000000'),
       (3, 5, '2022-08-15 09:36:49.000000', '2022-08-20 09:36:49.000000'),
       (4, 6, '2022-08-01 09:36:49.000000', '2022-08-20 09:36:49.000000'),
       (4, 7, '2022-07-01 09:36:49.000000', '2022-08-20 09:36:49.000000'),
       (5, 8, '2022-06-01 09:36:49.000000', '2022-08-20 09:36:49.000000'),
       (5, 12, '2022-05-01 09:36:49.000000', '2022-08-20 09:36:49.000000');